services:
  - type: worker
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip uninstall -y python-telegram-bot
      pip install -r requirements.txt --force-reinstall
    startCommand: ./start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
